### ISSUE TITLE
Game update possibly broken the plugin

### ISSUE THREAD

**Issue by skybleu** [viktor-ferenczi/toolbar-manager#13]
I spawned to the new scenario latest DLC added, tried to load toolbar I always use in vanilla worlds.
The game crashed right when it should load, then errored out when the game restarted.
Since I can't re-enable it, can't confirm if it's dependant on the scenario.

**Comment by RoCkHeLuCk** [comment]
I did the new update, when loading the error and it doesn't run, I tried deleting everything and installing everything again, but nothing. Looks like it's the new version of the game.

**Comment by viktor-ferenczi** [comment]
A new version will be released soon, which will fix the issue. It already works here, just tested it.

**Comment by viktor-ferenczi** [comment]
Toolbar Manager 1.3.4

- Compatibility with game version 1.203.022: Decorative Pack #3
- Harmony 2.2.2
