### ISSUE TITLE
shift + letter setting

### ISSUE THREAD

**Issue by Arbel-arad** [viktor-ferenczi/toolbar-manager#9]
please add an option to disable the shift + letter search
this causes problems when attempting to: run, use the shift placement modifier while moving.
thank you.

**Comment by Kaze-Kami** [comment]
Alternatively a different (maybe configurable) key bind (like press `=` then type) would be sufficient.
I think the feature is a great idea, just the fact that I can't sprint while it is enabled makes it rather unusable as of now and I'd rather keep sprinting on shift than move that to a different key.

**Comment by viktor-ferenczi** [comment]
Fixed by version 1.3.1, which requires CTRL+SHIFT+Letter to open the menu.

1.3.2 will add configuration, so this feature can be disabled or customized.
